x-globals: &globals
  environment:
    TZ: ${TZ}
    PUID: ${PUID}
    PGID: ${PGID}
  restart: unless-stopped

services:
  wireguard:
    <<: *globals
    image: linuxserver/wireguard:1.0.20210914
    container_name: wireguard
    ports:
      - "51820:51820/udp"
      # For caddy
      - "80:80"
      - "443:443"
    environment:
      INTERNAL_SUBNET : 10.10.10.0
      PEERS           : rpi01,pixel4a
    volumes:
      - ./wireguard:/config
      - /lib/modules:/lib/modules
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      net.ipv4.conf.all.src_valid_mark: 1

  caddy:
    <<: *globals
    container_name: caddy
    depends_on: [wireguard]
    network_mode: service:wireguard # Share wireguard VPN network
    build: .
    environment:
      DOMAIN: ${DOMAIN}
      EMAIL: ${EMAIL}
      CLOUDFLARE_API_TOKEN: ${CLOUDFLARE_API_TOKEN}
    volumes:
      - ./caddy/caddyfile:/etc/caddy/Caddyfile:ro
      - ./caddy/data:/data
      - ./caddy/config:/config

  fail2ban:
    <<: *globals
    image: crazymax/fail2ban:0.11.2
    container_name: fail2ban
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - ./fail2ban/data:/data
      - /var/log:/var/log:ro

  vaultwarden:
    <<: *globals
    image: vaultwarden/server:1.25.2-alpine
    container_name: vaultwarden
    environment:
      WEBSOCKET_ENABLED : 'true'
      SIGNUPS_ALLOWED   : 'false'
    volumes:
      - ./vaultwarden:/data

  ssh-chat:
    <<: *globals
    image: byreqz/ssh-chat:latest
    container_name: ssh-chat
    ports:
      - "2022:2022"
    volumes:
      - ./ssh-chat/ssh-chat-key:/ssh_key
      - ./ssh-chat/admin_keys:/admin_keys:ro
      - ./ssh-chat/motd:/motd
