---
version: '3.3'
services:
  wireguard:
    image: linuxserver/wireguard:1.0.20210914
    container_name: wireguard
    ports:
      - "51820:51820/udp"
      # For caddy
      - "80:80"
      - "443:443"
    environment:
      PEERS           : ${PEERS}
      INTERNAL_SUBNET : 10.10.10.0
      PUID            : ${PUID}
      PGID            : ${PGID}
      TZ              : ${TZ}
    volumes:
      - ${HOME}/bastion/wireguard:/config
      - /lib/modules:/lib/modules
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      net.ipv4.conf.all.src_valid_mark: 1
    restart: unless-stopped

  caddy:
    container_name: caddy
    depends_on: [wireguard]
    network_mode: service:wireguard # Share wireguard VPN network
    build: .
    environment:
      DOMAIN: ${DOMAIN}
      EMAIL: ${EMAIL}
      CLOUDFLARE_API_TOKEN: ${CLOUDFLARE_API_TOKEN}
    volumes:
      - ${HOME}/bastion/caddy/caddyfile:/etc/caddy/Caddyfile:ro
      - ${HOME}/bastion/caddy/data:/data
      - ${HOME}/bastion/caddy/config:/config
    restart: unless-stopped

  fail2ban:
    image: crazymax/fail2ban:0.11.1
    container_name: fail2ban
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - ${HOME}/bastion/fail2ban/data:/data
      - /var/log:/var/log:ro
    restart: unless-stopped
