services:
  headscale:
    image: headscale/headscale:0.22.3
    container_name: headscale
    command: headscale serve
    ports:
      - "8080:8080"
      - "9090:9090"
    volumes:
      - ./headscale/config:/etc/headscale
      - ./headscale/data:/var/lib/headscale
    restart: unless-stopped

  tailscale:
    image: tailscale/tailscale:v1.54.0
    container_name: tailscale
    hostname: oracle02
    command: tailscaled
    depends_on: [headscale]
    privileged: 'true'
    cap_add:
      - net_admin
      - sys_module
    ports:  # for caddy
      - "80:80"
      - "443:443"
    volumes:
      - ./tailscale:/var/lib
      - /dev/net/tun:/dev/net/tun
    restart: unless-stopped

  caddy:
    container_name: caddy
    build: .
    depends_on:
      - headscale
      - tailscale
    network_mode: service:tailscale # connect to VPN
    environment:
      DOMAIN: ${DOMAIN}
      EMAIL: ${EMAIL}
      CLOUDFLARE_API_TOKEN: ${CLOUDFLARE_API_TOKEN}
    volumes:
      - ./caddy/caddyfile:/etc/caddy/Caddyfile:ro
      - ./caddy/data:/data
      - ./caddy/config:/config
    restart: unless-stopped

  fail2ban:
    image: crazymax/fail2ban:0.11.2
    container_name: fail2ban
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - ${HOME}/bastion/fail2ban/data:/data
      - /var/log:/var/log:ro
    restart: unless-stopped
